[project]
name = "montecarlo-simulation-integral"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "numba==0.61.2",
    "numpy==2.2.6",
    "pandas>=2.3.2",
    "streamlit>=1.49.0",
]
